version: '3.9'

services:
  php-playground:
    build: ./web-app
    ports:
      - "8080:8080"
    volumes:
      - "/usr/local/src/php-playground/:/usr/local/src/php-playground/"
      - "/var/run/docker.sock:/var/run/docker.sock"
